/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-mode="dark"]'],
  theme: {
    extend: {
      colors: {
        // The main colors depend on whether using light/dark theme, so must use variables
        main: {
          piccolo: "rgb(var(--color-piccolo))",
          jiren: "rgba(var(--color-jiren), var(--opacity-jiren))",
          hit: "rgb(var(--color-hit))",
          heles: "rgba(var(--color-heles), var(--opacity-heles))",
          beerus: "rgb(var(--color-beerus))",
          goku: "rgb(var(--color-goku))",
          gohan: "rgb(var(--color-gohan))",
          zeno: "rgba(var(--color-zeno), var(--opacity-zeno))",
          bulma: "rgb(var(--color-bulma))",
          trunks: "rgb(var(--color-trunks))",
          goten: "rgb(var(--color-goten))",
          popo: "rgb(var(--color-popo))",
        },
        supportive: {
          "krillin-100": "rgb(var(--supportive-krillin))",
          "krillin-60": "rgba(var(--supportive-krillin), 0.56)",
          "krillin-10": "rgba(var(--supportive-krillin), 0.12)",
          "chiChi-100": "rgb(var(--supportive-chiChi))",
          "chiChi-60": "rgba(var(--supportive-chiChi), 0.56)",
          "chiChi-10": "rgba(var(--supportive-chiChi), 0.12)",
          "roshi-100": "rgb(var(--supportive-roshi))",
          "roshi-60": "rgba(var(--supportive-roshi), 0.56)",
          "roshi-10": "rgba(var(--supportive-roshi), 0.12)",
          "dodoria-100": "rgb(var(--supportive-dodoria))",
          "dodoria-60": "rgba(var(--supportive-dodoria), 0.56)",
          "dodoria-10": "rgba(var(--supportive-dodoria), 0.12)",
          "cell-100": "rgb(var(--supportive-cell))",
          "cell-60": "rgba(var(--supportive-cell), 0.56)",
          "cell-10": "rgba(var(--supportive-cell), 0.12)",
          "raditz-100": "rgb(var(--supportive-raditz))",
          "raditz-60": "rgba(var(--supportive-raditz), 0.56)",
          "raditz-10": "rgba(var(--supportive-raditz), 0.12)",
          "whis-100": "rgb(var(--supportive-whis))",
          "whis-60": "rgba(var(--supportive-whis), 0.56)",
          "whis-10": "rgba(var(--supportive-whis), 0.12)",
          "frieza-100": "rgb(var(--supportive-frieza))",
          "frieza-60": "rgba(var(--supportive-frieza), 0.56)",
          "frieza-10": "rgba(var(--supportive-frieza), 0.12)",
          "nappa-100": "rgb(var(--supportive-nappa))",
          "nappa-60": "rgba(var(--supportive-nappa), 0.56)",
          "nappa-10": "rgba(var(--supportive-nappa), 0.12)",
        },
      },
      textColor: {
        main: {
          piccolo: "rgb(var(--color-goten))",
          jiren: "rgb(var(--text-jiren))",
          hit: "rgb(var(--text-hit))",
          heles: "rgb(var(--text-heles))",
          beerus: "rgb(var(--text-beerus))",
          goku: "rgb(var(--text-goku))",
          gohan: "rgb(var(--text-gohan))",
          zeno: "rgb(var(--color-goten))",
          bulma: "rgb(var(--text-bulma))",
          trunks: "rgb(var(--color-goten))",
          goten: "rgb(var(--text-goten))",
          popo: "rgb(var(--text-popo))",
        },
        supportive: {
          "krillin-100": "rgb(var(--main-goten))",
          "krillin-60": "rgb(var(--main-bulma))",
          "krillin-10": "rgb(var(--main-bulma))",
          "chiChi-100": "rgb(var(--main-goten))",
          "chiChi-60": "rgb(var(--main-bulma))",
          "chiChi-10": "rgb(var(--main-bulma))",
          "roshi-100": "rgb(var(--main-goten))",
          "roshi-60": "rgb(var(--main-bulma))",
          "roshi-10": "rgb(var(--main-bulma))",
          "dodoria-100": "rgb(var(--main-goten))",
          "dodoria-60": "rgb(var(--main-bulma))",
          "dodoria-10": "rgb(var(--main-bulma))",
          "cell-100": "rgb(var(--main-bulma))", // Yes, cell-100 is supposed to have --main-bulma text color
          "cell-60": "rgb(var(--main-bulma))",
          "cell-10": "rgb(var(--main-bulma))",
          "raditz-100": "rgb(var(--main-goten))",
          "raditz-60": "rgb(var(--main-bulma))",
          "raditz-10": "rgb(var(--main-bulma))",
          "whis-100": "rgb(var(--main-goten))",
          "whis-60": "rgb(var(--main-bulma))",
          "whis-10": "rgb(var(--main-bulma))",
          "frieza-100": "rgb(var(--main-goten))",
          "frieza-60": "rgb(var(--main-bulma))",
          "frieza-10": "rgb(var(--main-bulma))",
          "nappa-100": "rgb(var(--main-goten))",
          "nappa-60": "rgb(var(--main-bulma))",
          "nappa-10": "rgb(var(--main-bulma))",
        },
      },
    },
  },
  plugins: [],
};
